[build]
  command = "yarn build"
  publish = ".next"

[functions]
  external_node_modules = ["styled-jsx", "next/dist/compiled/find-up"]
  included_files = ["node_modules/styled-jsx/**/*", "node_modules/next/dist/compiled/find-up/**/*"]

[[plugins]]
  package = "@netlify/plugin-nextjs" 