[build]
  command = "yarn build --no-lint"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Increase function timeout for LLM endpoints
[[functions]]
  path = "app/api/agents/*/questions/*"
  timeout = 30

[[functions]]
  path = "app/api/**"
  timeout = 26

# Environment variables that must be set on Netlify
[template.environment]
  GOOGLE_API_KEY = "Google API key for Gemini models"
  PINECONE_API_KEY = "Pinecone API key"
  PINECONE_INDEX = "Name of your Pinecone index"
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "Your Clerk publishable key"
  CLERK_SECRET_KEY = "Your Clerk secret key"
  NEXT_PUBLIC_CLERK_AFTER_SIGN_OUT_URL = "Your deployed Netlify app URL (e.g., https://your-app.netlify.app)" 