[build]
  command = "NODE_OPTIONS='--max_old_space_size=4096' yarn build --no-lint"
  publish = ".next"

[build.environment]
NEXT_TELEMETRY_DISABLED = "1"
NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Function configurations
[functions]
  node_bundler = "esbuild"

[functions."app/api/agents/*/questions/*"]
  timeout = 30

[functions."app/api/**"]
  timeout = 30

# Environment variables that must be set on Netlify
[template.environment]
  GOOGLE_API_KEY = "Google API key for Gemini models"
  PINECONE_API_KEY = "Pinecone API key"
  PINECONE_INDEX = "Name of your Pinecone index"
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "Your Clerk publishable key"
  CLERK_SECRET_KEY = "Your Clerk secret key"
  NEXT_PUBLIC_CLERK_AFTER_SIGN_OUT_URL = "Your deployed Netlify app URL (e.g., https://your-app.netlify.app)" 